CT/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, re_path, include
from django.views.generic.base import TemplateView

app_name = 'CT'
urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^home/$', views.home, name='home'),
    path('about/', TemplateView.as_view(template_name='CT/about.html'), name='About'),
    path('', views.client_list, name='client_list'),
    path('client_list', views.client_list, name='client_list'),
    path('client/<int:pk>/edit/', views.client_edit, name='client_edit'),
    path('client/<int:pk>/delete/', views.client_delete, name='client_delete'),
    path('mealtrack_list', views.mealtrack_list, name='mealtrack_list'),
    path('mealtrack/add/', views.mealtrack_new, name='mealtrack_new'),
    path('mealtrack/<int:pk>/edit/', views.mealtrack_edit, name='mealtrack_edit'),
    path('mealtrack/<int:pk>/delete/', views.mealtrack_delete, name='mealtrack_delete'),
    path('client/<int:pk>/summary/', views.summary, name='summary'),
    path('bmrcalc/', TemplateView.as_view(template_name='CT/BMRCalculator.html'), name='BMRCalculator'),

]

CalTracker/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('CT.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('about/', TemplateView.as_view(template_name='CT/about.html'), name='About'),
    path('signup/', TemplateView.as_view(template_name='registration/signup.html'), name='About'),

]

accounts/urls.py
# accounts/urls.py
from django.urls import path, include

from .views import SignUpView


urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('accounts/', include('accounts.urls')),
]

CT/models.py
from django.utils import timezone
from django.db import models


# Create your models here.
class Client(models.Model):
    CHOICE = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )
    client_name = models.CharField(max_length=50)
    gender = models.CharField(max_length=50, choices=CHOICE)
    email = models.EmailField(max_length=100)
    address = models.CharField(max_length=200)
    height = models.IntegerField(blank=False, null=False)
    weight = models.IntegerField(blank=False, null=False)
    client_age = models.IntegerField(blank=False, null=False)
    BMR = models.DecimalField(max_digits=10, decimal_places=2)
    account_number = models.IntegerField(blank=False, null=False)
    city = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=10)
    phone_number = models.CharField(max_length=50)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.client_name)


class MealTracker(models.Model):
    CHOICES = (
        ('Breakfast', 'Breakfast'),
        ('Lunch', 'Lunch'),
        ('Dinner', 'Dinner'),
        ('Snack', 'Snack')
    )
    client_name = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='mealtrack')
    meal_category = models.CharField(max_length=50, choices=CHOICES)
    meal_description = models.TextField()
    time = models.DateTimeField(
        default=timezone.now)
    calories = models.DecimalField(max_digits=10, decimal_places=2)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.client_name)

CT/forms.py
from django import forms
from .models import Client, MealTracker


class ClientForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ('client_name', 'gender', 'email', 'height', 'weight', 'client_age', 'BMR', 'account_number', 'address',
                  'city', 'state', 'zipcode', 'phone_number')


class MealTrackerForm(forms.ModelForm):
    class Meta:
        model = MealTracker
        fields = ('client_name', 'meal_category', 'meal_description', 'time', 'calories')

CT/views.py
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.db.models import Sum
from _decimal import Decimal

now = timezone.now()


def home(request):
    return render(request, 'CT/home.html',
                  {'CT': home})


@login_required
def client_list(request):
    client = Client.objects.filter(created_date__lte=timezone.now())
    return render(request, 'CT/client_list.html',
                  {'clients': client})


@login_required
def client_edit(request, pk):
    client = get_object_or_404(Client, pk=pk)
    if request.method == "POST":
        # update
        form = ClientForm(request.POST, instance=client)
        if form.is_valid():
            client = form.save(commit=False)
            client.updated_date = timezone.now()
            client.save()
            client = Client.objects.filter(created_date__lte=timezone.now())
            return render(request, 'CT/client_list.html',
                          {'clients': client})
    else:
        # edit
        form = ClientForm(instance=client)
    return render(request, 'CT/client_edit.html', {'form': form})


@login_required
def client_delete(request, pk):
    client = get_object_or_404(Client, pk=pk)
    client.delete()
    return redirect('CT:client_list')


@login_required
def mealtrack_list(request):
    mealtracks = MealTracker.objects.filter(created_date__lte=timezone.now())
    return render(request, 'CT/mealtrack_list.html', {'mealtracks': mealtracks})


@login_required
def mealtrack_new(request):
    if request.method == "POST":
        form = MealTrackerForm(request.POST)
        if form.is_valid():
            mealtracks = form.save(commit=False)
            mealtracks.created_date = timezone.now()
            mealtracks.save()
            mealtracks = MealTracker.objects.filter(created_date__lte=timezone.now())
            return render(request, 'CT/mealtrack_list.html',
                          {'mealtracks': mealtracks})
    else:
        form = MealTrackerForm()
        # print("Else")
    return render(request, 'CT/mealtrack_new.html', {'form': form})


@login_required
def mealtrack_edit(request, pk):
    mealtrack = get_object_or_404(MealTracker, pk=pk)
    if request.method == "POST":
        form = MealTrackerForm(request.POST, instance=mealtrack)
        if form.is_valid():
            mealtrack = form.save()
            # mealtrack.client = mealtrack.id
            mealtrack.updated_date = timezone.now()
            mealtrack.save()
            mealtracks = MealTracker.objects.filter(created_date__lte=timezone.now())
            return render(request, 'CT/mealtrack_list.html', {'mealtracks': mealtracks})
    else:
        # print("else")
        form = MealTrackerForm(instance=mealtrack)
    return render(request, 'CT/mealtrack_edit.html', {'form': form})


@login_required
def mealtrack_delete(request, pk):
    mealtrack = get_object_or_404(MealTracker, pk=pk)
    mealtrack.delete()
    return redirect('CT:mealtrack_list')

@login_required
def summary(request, pk):
    client = get_object_or_404(Client, pk=pk)
    clients = Client.objects.filter(created_date__lte=timezone.now())
    tracker = MealTracker.objects.filter(client_name=pk)

    sum_calories = \
        MealTracker.objects.filter(client_name=pk).aggregate(Sum('calories'))

    sum = sum_calories.get("calories__sum")
    if sum == None:
        sum_calories = {'calories__sum' : Decimal('0')}



    return render(request, 'CT/summary.html', {'client': client,
                                                'tracker': tracker,
                                                'clients': clients,
                                                'sum_calories': sum_calories, })

accounts/views.py
# accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

CT/templates/CT/BMRCalculator.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<title>BMR Calculator</title>
<body>

    <div class="about-section">
        <img class="pic" src="{% static "images/logo.JPG" %}" alt="Logo" width="140" height="140"/>
        <h1>Calculating BMR at Calorie Tracker</h1>
            <p>At Calorie Tracker, we have studied methods and formulas to calculate the BMR for our clients.
                The Basal Metabolic Rate (BMR) Calculator estimates your basal metabolic rate—the amount of energy
                expended while at rest in a neutrally temperate environment, and in a post-absorptive state
                (meaning that the digestive system is inactive, which requires about 12 hours of fasting). However, we understand
                that calorie intake varies from person to person based on activity levels. For this reason, we use an external calculator
                that takes our client information and then compares it to certain activity levels which we can discuss with our client. The formulas
                below are the source of how these estimates are found! These BMR findings for the client are then shown on the summary page, which
                is compared to the daily calorie count tracked by our tracking algorithm.
            </p>

        <H4>Calorie Tracker For Men</H4>
        <body>Mifflin-St Jeor Equation : 10W + 6.25H  - 5A + 5</body><br>
        <body>Harris-Benedict Equation : 13.397W + 4.799H - 5.677A + 88.362</body>
        <H4>Calorie Tracker For Women</H4>
        <body>Mifflin-St Jeor Equation : 10W + 6.25H - 5A - 161</body><br>
        <body>Harris-Benedict Equation : 9.247W + 3.098H - 4.330A + 447.593</body>

        <body1></body1>

        <body>** NOTE ** : <br>
        W = Weight in kilograms (kg) <br>
        H = Height in centimeters (cm) <br>
        A = Age</body>

    </div>

    <footer></footer>
    <h1> -- Calculate Client BMR Here --</h1>
    <p><a href="https://www.calculator.net/bmr-calculator.html">
    <img src="{% static "images/BMR.jpg" %}" width="100" height="132">
    </a></p>


    <div style="text-align:center">
        <a href="{% url 'CT:home' %}" class="return"> Return Home</a>
        <a href="{% url 'CT:client_list' %}" class="return"> Update BMR</a>

    </div>

</body>

<style>

    body {

    text-align: center;
    color: grey;
    font-family: "Palatino Linotype", Palatino, serif;
}

html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}

.about-section {
  padding: 60px;
  text-align: center;
  background-color: lightgrey;
  color: black;
}


@media screen and (max-width: 650px) {
  .column {
    width: 100%;
    display: block;
  }
}

    .pic {
        position: absolute;
        top: 8px;
        left: 16px;
        padding-bottom: 30px;
        padding-top:  10px;
        padding-left: 10px;
        padding-right: 10px;


    }

    .return {
        border: none;
        margin-bottom: 25px;
        display: inline-block;
        padding: 8px;
        color: black;
        background-color: aqua;
        text-align: center;
        cursor: pointer;
        width: 10%;
    }

    h4 {
 font-family: "Palatino Linotype", Palatino, serif;
 font-size: 15px;
 color: black;
}

footer {
 font-size: 0.75em;
 text-align: center;
 margin-left: 20px;
 clear: both;
 color: #ccc;
 }



</style>


</html>

CT/templates/CT/about.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

    <title>About</title>
<body>

    <div class="about-section">
        <img class="pic" src="{% static "images/logo.JPG" %}" alt="Logo" width="140" height="140"/>
        <h1>The Calorie Tracker Story</h1>
            <p>The Calorie Tracker Application is developed for individuals who strive
                to maintain healthy diets and keep a consistent watch on their daily calorie intake.
                As developers, we have designed a program to allow users to input each meal and track their
                daily calorie intake and then compare it to results found by formulas that show factors such as
                body mass index and metabolic rates connected to the user. This allows our users to set goals and have a
                reliable source to help maintain them. Our goal at Calorie Tracker is to ensure our users have a reliable, functional platform that gives them an opportunity to
                live healthy lives. We understand the need for healthy diets in people of all ages, so we have designed an interphase simple enough for
                any type of user. We will continue to enhance the application and accompany any user wants through updates in the future.</p>

        <p2> Thank you so much for choosing Calorie Tracker for your everyday health needs. Please scroll down to meet the team behind the application
                foundation and development!</p2>


    </div>

        <h2 style="text-align:center">Our Team</h2>
            <div class="row">
                <div class="column">
                    <div class="card">
                        <img class="picZ" src="{% static "images/ZTPic.jpg" %}" alt="Zach" width="100%"/>
                        <div class="container">
                            <h2>Zach Thornhill</h2>
                            <p class="title">Developer</p>
                            <p>Hello, my name is Zach Thornhill and I am a senior at UNO. I am majoring in MIS with an Information Assurance concentration
                                and also securing a Business Minor. Along with my studies, I am a student-athlete on the Men's Basketball
                                team at UNO. As an athlete, I understand the need for a healthy diet so my passion for developing an application
                                that helps accomplish this is very high!</p>
                            <p>zthornhill@unomaha.edu</p>
                        <p1><button class="button"><a href="mailto:zthornhill@unomaha.edu">Contact Me</a></button></p1>
                        </div>
                    </div>
                </div>

            <div class="column">
                <div class="card">
                    <img class="picZ" src="{% static "images/NoahW.JPG" %}" alt="Noah" width="100%"/>
                    <div class="container">
                        <h2>Noah Wagner</h2>
                        <p class="title">Developer</p>
                        <p>Hello all, my names Noah Wagner and I'm currently a senior at UNO. I major in Management Information Systems (MIS) as well as obtaining my
                            certificate for being a System Developer and I plan on graduating in May 2021. I take special interest in developing this application as it
                            provides many benefits for various users. Health is critical for each and every person and everyone should strive for good health!</p>
                        <p>ncwagner@unomaha.edu</p>
                        <p1><button class="button"><a href="mailto:ncwagner@unomaha.edu">Contact Me</a></button></p1>
                    </div>
                </div>
            </div>

  <div class="column">
    <div class="card">
     <img class="picZ" src="{% static "images/CoreyS.jpg" %}" alt="Noah" width="100%"/>
      <div class="container">
        <h2>Corey Snavely</h2>
        <p class="title">Developer</p>
        <p>Hey everyone, my name is Corey Snavely and I'm a senior at UNO. I am majoring in Management Information Systems and I
            am planning to graduate in May of 2021. I'm proud of the Calorie Tracker application we have developed because it shows the
            good that can come from work in the Information Technology field and the importance it can have on the average person's daily life.
        </p>
        <p>csnavely@unomaha.edu</p>
        <p1><button class="button"><a href="mailto:csnavely@unomaha.edu">Contact Me</a></button></p1>
      </div>
    </div>
  </div>
</div>

    <div style="text-align:center">
        <a href="{% url 'CT:home' %}" class="return"> Return Home</a>

    </div>

</body>

<style>

    body {
  font-family: Arial, Helvetica, sans-serif;
  margin: 0;
}

html {
  box-sizing: border-box;
}

*, *:before, *:after {
  box-sizing: inherit;
}

.column {
  float: left;
  width: 33.3%;
  margin-bottom: 16px;
  padding: 0 8px;
}

.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  margin: 8px;
}

.about-section {
  padding: 60px;
  text-align: center;
  background-color: lightgrey;
  color: black;
}

.container {
  padding: 0 16px;
}

.container::after, .row::after {
  content: "";
  clear: both;
  display: table;
}

.title {
  color: grey;
}

.button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
}

.button:hover {
  background-color: #555;
}

@media screen and (max-width: 650px) {
  .column {
    width: 100%;
    display: block;
  }
}

    .pic {
        position: absolute;
        top: 8px;
        left: 16px;
        padding-bottom: 30px;
        padding-top:  10px;
        padding-left: 10px;
        padding-right: 10px;


    }

    .return {
        border: none;
        margin-bottom: 25px;
        display: inline-block;
        padding: 8px;
        color: black;
        background-color: aqua;
        text-align: center;
        cursor: pointer;
        width: 10%;
    }

    a {
        color: white;
    }

</style>


</html>

CT/templates/CT/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <title>Calorie Tracker</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 20px;
            border-radius: 10px;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 600px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 100px;
            background-color: aqua;
            height: 100%;
        }


        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }
    </style>
</head>
<body id="app-layout">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="/">
                Calorie Tracker
            </a>

            <style>

                .navbar-brand{
                    color: aqua;
                }

            </style>

        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'CT:home' %}">Home</a></li>
                <li><a href="{% url 'CT:client_list' %}">Clients</a></li>
                <li><a href="{% url 'CT:mealtrack_list' %}">Meal Tracker</a></li>
                <li><a href="{% url 'CT:BMRCalculator' %}">BMR Calculation</a></li>
                <li><a href="{% url 'CT:About' %}">About</a></li>

                {% load static %}

    <img class="pic" src="{% static "images/logo.JPG" %}" alt="Logo" width="150" height="150"/>
    <img class="pic2" src="{% static "images/logo.JPG" %}" alt="Logo" width="150" height="150"/>

    <style>

    .pic {
    position:fixed;
	top: 100px;
	left: 25px;
    }

    .pic2 {
    position:fixed;
	top:100px;
	right: 25px;
    }

    </style>

            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                    <li><a href="{% url 'password_reset' %}"><span class="glyphicon glyphicon-log-in"></span> Reset Password</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="content container">
    <div class="row">
        <div class="col-md-8">
            {% block content %}
                <div class="links">
                    <!-- Example row of columns -->
                    <div class="row">
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/Clients.jpg" %}" alt="client"/>
                                <div class="caption">
                                    <h3>Clients</h3>
                                    <p>Ensuring our clients are given the opportunity to track their nutrition
                                        goals is our mission</p>
                                    {% if user.is_authenticated %}
                                        <p><a class="btn btn-default" href="{% url 'CT:client_list' %}"
                                              role="button">View
                                            details &raquo;</a></p>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="thumbnail">
                                <img src="{% static "images/MTrack.jpg" %}" alt="mTrack"/>
                                <div class="caption">
                                    <h3>Meal Tracker</h3>
                                    <p>Full meal catalogs overseen by our nutrition professionals
                                        help track client progress in their nutrition goals</p>
                                    <p><a class="btn btn-default" href="{% url 'CT:mealtrack_list' %}"
                                           role="button">View
                                        details &raquo;</a></p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            {% endblock %}
        </div>
    </div>
</body>

<footer>
    <h4>Email Us!</h4>
  <p>Authors: Noah Wagner, Corey Snavely, Zach Thornhill, Mark Kroeker</p>
  <p><a href="mailto:ncwagner@unomaha.edu">Noah Wagner</a></p>
  <p><a href="mailto:zthornhill@unomaha.edu">Zach Thornhill</a></p>
  <p><a href="mailto:csnavely@unomaha.edu">Corey Snavely</a></p>

</footer>

</html>

<style>

    body{
        background: lightgrey;
    }

    .col-md-3 {
        width: 700px;
        align-content: center;
        margin-left: 250px;
        background: gray;
        font-family: Impact;
        text-align: center;
        color: black;
    }

    /*************************************
FOOTER
**************************************/
     footer {
         font-size: 10px;
         text-align: center;
         align-self: center;
         margin-left: 300px;
         margin-right: 300px;
         width: 50%;
         clear: both;
         color: black;
         margin-bottom: 5px;
     }

</style>

CT/templates/CT/client_delete.html
<!DOCTYPE html>
<html lang="en">
{% block body_block %}
    <h1>Delete {{ client.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'CT:home' pk=client.client_number %} ">Cancel</a>

    </form>

{% endblock %}

</html>

CT/templates/CT/client_list.html
<!DOCTYPE html>
<html lang="en">
{% extends 'CT/base.html' %}
{% block content %}

    <html>
    <head>
        <meta charset="UTF-8">
        <title>Calorie Tracker</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: aqua;
        }
    </style>
<div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome to the Calorie Tracker</div>
                    <div class="panel-body">
                        Turning Client's Nutrition Goals into Reality!
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left:15Px">Client Information</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Client Name</th>
                <th>Gender</th>
                <th>Email</th>
                <th>Height</th>
                <th>Weight</th>
                <th>Age</th>
                <th>BMR</th>
                <th>Acc Number</th>
                <th>Phone Number</th>
                <th>Address</th>
                <th>City</th>
                <th>State</th>
                <th>Zip Code</th>

                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for client in clients %}
                <tr>
                    <td>{{ client.client_name }}</td>
                    <td>{{ client.gender }}</td>
                    <td>{{ client.email }}</td>
                    <td>{{ client.height }}</td>
                    <td>{{ client.weight }}</td>
                    <td>{{ client.age }}</td>
                    <td>{{ client.BMR }}</td>
                    <td>{{ client.account_number }}</td>
                    <td>{{ client.phone_number }}</td>
                    <td>{{ client.address }}</td>
                    <td>{{ client.city }}</td>
                    <td>{{ client.state }}</td>
                    <td>{{ client.zipcode }}</td>

                   <td><a href="{% url 'CT:client_edit' pk=client.pk %}" class="btn btn-warning">Edit</a>

                   <td><a href="{% url 'CT:client_delete' pk=client.pk %}"
                          onclick="return confirm('Are you sure you want to delete this Client?')"
                          class="btn btn-danger">Delete</a>
                   </td>

                    <td><a href="{% url 'CT:summary' pk=client.pk %}"
                           class="btn btn-primary">Summary</a>

                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
    </body>

    <style>

        .panel-body{
            text-align: center;
        }

        .panel-heading{
            text-align: center;
        }

        .row{
            text-align: center;
            padding: 5px;
        }

    </style>
    </html>
{% endblock %}
</html>

CT/templates/CT/mealtrack_delete.html
<!DOCTYPE html>
<html lang="en">
{% block body_block %}
    <h1>Delete {{ mealtrack.name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'CT:home' pk=mealtrack.mealtrack_number %} ">Cancel</a>

    </form>

{% endblock %}

</html>

CT/templates/CT/mealtrack_list.html
<!DOCTYPE html>
{% extends 'CT/base.html' %}
{% block content %}
    <head>
        <meta charset="UTF-8">
        <title>Calorie Tracker</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: aqua;
        }

        .row{
            text-align: center;
            padding: 5px;
        }

        .panel-heading{
            text-align: center;
        }

        .panel-body{
            text-align: center;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome to the Calorie Tracker!</div>
                    <div class="panel-body">
                        Turning Client's Nutrition Goals into Reality!
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Client Meal Tracking</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Client</th>
                <th>Meal Category</th>
                <th>Meal Description</th>
                <th>Meal Time</th>
                <th>Calorie Count</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for mealtrack in mealtracks %}
                <tr>
                    <td>{{ mealtrack.client_name }}</td>
                    <td>{{ mealtrack.meal_category }}</td>
                    <td>{{ mealtrack.meal_description }}</td>
                    <td>{{ mealtrack.time }}</td>
                    <td>{{ mealtrack.calories }}</td>
                    <td><a href="{% url 'CT:mealtrack_edit' pk=mealtrack.pk %}"
                           class="btn btn-warning">Edit</a></td>
                    <td><a href="{% url 'CT:mealtrack_delete' pk=mealtrack.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
</td>

                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>

    <div class="row">
         <a href="{% url 'CT:mealtrack_new' %}" class="row"><span
                    class="btn btn-primary">Add Meal</span></a>
     </div>


    </body>
{% endblock %}